# Generated by Django 5.0.3 on 2024-03-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_price_task_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='price',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
